import "./globals.css";
import type { Metadata } from "next";
import Footer from "@next/components/Footer";
import Header from "@next/components/Header";

export const metadata: Metadata = {
  title: "Pawttage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/dog.png" sizes="any" />
      </head>
      <body>
        <Header />
        <div className="w-full min-h-full grid place-items-center px-20 py-16">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
